version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install --omit=dev --legacy-peer-deps
      - aws cloudformation package --template-file template.yaml --s3-bucket mother-code-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
    - configuration-prod.json
    - activities/**/*
    - ajax/**/*
    - public/**/*
    - app.js