version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --omit=dev
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
    - configuration-prod.json
    - activities/**/*
    - ajax/**/*
    - public/**/*
    - app.js
    - creds.json