version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --omit=dev --legacy-peer-deps
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-ap-southeast-2-262985664461 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
    - configuration-prod.json
    - activities/**/*
    - ajax/**/*
    - public/**/*
    - app.js
    - creds.json