version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mother"
s3_bucket = "mother-code-pipeline"
s3_prefix = "mother"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
