org: ${env:ORG}
app: ${env:APP}
service: ${env:SERVICE}
frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-southeast-2
  memorySize: 256
  environment:
    NODE_ENV: ${env:NODE_ENV}
    SSM_PATH_SECRET: ${env:SSM_PATH_SECRET}
    ORG: ${env:ORG}
    AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: ${env:AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE}

functions:
  app:
    timeout: 28
    handler: app.handler
    events:
      - http: 'ANY /public/{proxy+}'
      - http: 'ANY /ajax/{proxy+}'
      - http: 'GET /'
      - http: 'GET /index.html'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverless-offline:
    httpsProtocol: "cert"
    httpPort: 443
    noPrependStageInUrl: true